### ISSUE TITLE
run_demo.py not found and demo_ui.py not launching UI

### ISSUE THREAD

**Issue by rbinnun** [deepmind/spriteworld#1]
I'm trying to run the demo described on the project page, but I'm not finding `run_demo.py` in the distribution (installed using `pip install spriteworld`) and the closest sounding file, `demo_ui.py` doesn't launch a UI  (tried both on Linux and Windows).

How should the demo be launched?

**Comment by Azhag** [comment]
Hello!

Thanks for checking our environment out :)

We actually decided not to put the two example scripts (`run_demo.py` and `example_run_loop.py`) or the tests into the pip repository (just for simplicity mostly, that way you only install the actual library).

So if you'd like to run the demo, you should download the `run_demo.py` file directly from Github  (https://github.com/deepmind/spriteworld/blob/master/run_demo.py, click Raw and right-click -> Save as), place it anywhere you like, and run it (it will instantiate a UI using demo_ui.py).
Alternatively, you can clone the repo using git directly (see option 3 in the Installation, https://github.com/deepmind/spriteworld#installation), which will download the run_demo.py file as well.

Sorry for the confusion, let me know if this works for you

**Comment by rbinnun** [comment]
Thanks Azhag, I downloaded the file and all is well!
